version: '3'
services:
  margin:
    container_name: margin-bot-2
    restart: always
    env_file:
      - base.env
    build: .
    links:
      - mongodb
  # mongodb:
  #   container_name: mongodb
  #   image: mongo
  #   ports:
  #     - '27017:27017'
